export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM_REQUEST = 'CART_REMOVE_ITEM_REQUEST'
export const CART_REMOVE_ITEM_SUCCESS = 'CART_REMOVE_ITEM_SUCCESS'
export const CART_REMOVE_ITEM_FAIL = 'CART_REMOVE_ITEM_FAIL'

export const CART_CREATE_ITEM_REQUEST = 'CART_CREATE_ITEM_REQUEST'
export const CART_CREATE_ITEM_SUCCESS = 'CART_CREATE_ITEM_SUCCESS'
export const CART_CREATE_ITEM_FAIL = 'CART_CREATE_ITEM_FAIL'

export const CART_DETAILS_REQUEST = 'CART_DETAILS_REQUEST'
export const CART_DETAILS_SUCCESS = 'CART_DETAILS_SUCCESS'
export const CART_DETAILS_FAIL = 'CART_DETAILS_FAIL'

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'